### ISSUE TITLE
rspamd-1.7.7 rspamd-1.7.8  libressl error RSA_get0_key

### ISSUE THREAD

**Issue by androdev4u** [vstakhov/rspamd#2347]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.7 1.7.8

### Operation system, CPU, memory and environment:
Gentoo Linux:

Portage 2.3.43 (python 3.5.5-final-0, default/linux/amd64/17.0/systemd, gcc-7.3.0, glibc-2.27-r5, 4.17.3-gentoo-xen-dom0-blktap x86_64)
=================================================================
System uname: Linux-4.17.3-gentoo-xen-dom0-blktap-x86_64-Intel-R-_Core-TM-_i3-6300_CPU_@_3.80GHz-with-gentoo-2.6
KiB Mem:     8055588 total,   4211440 free
KiB Swap:    8380412 total,   8379636 free
Timestamp of repository gentoo: Mon, 16 Jul 2018 12:30:01 +0000
Head commit of repository gentoo: 0415982f15fb09367fc8595e25d1aad16ae6600d
sh bash 4.4_p23
ld GNU ld (Gentoo 2.30 p3) 2.30.0
app-shells/bash:          4.4_p23::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15::gentoo, 3.5.5-r1::gentoo
dev-util/cmake:           3.11.4::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.69-r4::gentoo
sys-devel/automake:       1.15.1-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.29.1-r1::gentoo, 2.30-r3::gentoo
sys-devel/gcc:            6.4.0-r1::gentoo, 7.3.0-r3::gentoo
sys-devel/gcc-config:     1.9.1::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r3::gentoo
sys-kernel/linux-headers: 4.17::gentoo (virtual/os-headers)
sys-libs/glibc:           2.27-r5::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts: 
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-jobs: 1

libressl
    location: /var/lib/layman/libressl
    masters: gentoo
    priority: 1

pentoo
    location: /var/lib/layman/pentoo
    masters: gentoo
    priority: 2

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -U_FORTIFY_SOURCE"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/easy-rsa /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.0/ext-active/ /etc/php/apache2-php7.1/ext-active/ /etc/php/apache2-php7.2/ext-active/ /etc/php/cgi-php7.0/ext-active/ /etc/php/cgi-php7.1/ext-active/ /etc/php/cgi-php7.2/ext-active/ /etc/php/cli-php7.0/ext-active/ /etc/php/cli-php7.1/ext-active/ /etc/php/cli-php7.2/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe -U_FORTIFY_SOURCE"
DISTDIR="/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--keep-going y -t"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="de_DE.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="de dk fi jp it tr nl fr"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="acl amd64 apache apache2 bcmath berkdb branding bzip2 bzlib calendar cli crypt ctype curl curlwrappers cxx dba dbase dbx dio dri dvd emacs encode exif fam flatfile fortran ftp gd gdbm gmp gudev iconv idn imap ipv6 jpeg ldap libressl libtirpc mad maildir mhash mime mmx mng modules mssql multilib mysql mysqli ncurses nls nptl nptlonly openmp pam pcre pdf pdflib php pic png posix readline samba seccomp session sharedext simplexml soap sockets spell sse sse2 ssl static-libs systemd sysvipc tcpd tidy tiff truetype udev unicode upcall usb vhost xattr xen xml2 xmlrpc xpm xsl zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="actions alias auth_basic auth_digest authn_anon authn_dbd authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock dbd deflate dir disk_cache env expires ext_filter file_cache filter headers ident imagemap include info log_config logio mem_cache mime mime_magic negotiation proxy proxy_ajp proxy_balancer proxy_connect proxy_http rewrite setenvif so speling status unique_id userdir usertrack vhost_alias authn_core ratelimit socache_shmcb slotmem_shm mysqli access_compat authz_core unixd mpm-prefork suexec" APACHE2_MPMS="prefork" CALLIGRA_FEATURES="karbon plan sheets stage words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-1" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="jython2_7 python2_7 jython3_5 python3_5" RUBY_TARGETS="ruby23" USERLAND="GNU" VIDEO_CARDS="vesa vga" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

### Description (Please provide a descriptive summary of the issue):

Fails to compile with libressl in version 1.7.7. Works with 1.7.5.

### Compile errors (if any):

../librspamd-server.a(dkim.c.o): In function `rspamd_dkim_match_keys':
/var/tmp/portage/mail-filter/rspamd-1.7.7/work/rspamd-1.7.7/src/libserver/dkim.c:3024: undefined reference to `RSA_get0_key'
/var/tmp/portage/mail-filter/rspamd-1.7.7/work/rspamd-1.7.7/src/libserver/dkim.c:3025: undefined reference to `RSA_get0_key'
collect2: error: ld returned 1 exit statu

### Steps to reproduce:

make

### Expected results:

builds

### Actual results:

fails to build

### Additional information:

rspamd-libressl.patch:

--- a/src/libserver/dkim.c	2018-07-17 11:42:51.655683687 +0200
+++ b/src/libserver/dkim.c	2018-07-17 11:44:29.707490647 +0200
@@ -3020,7 +3020,7 @@
 		return FALSE;
 	}
 
-#if OPENSSL_VERSION_NUMBER >= 0x10100000L
+#if OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined LIBRESSL_VERSION_NUMBER
 	RSA_get0_key (pk->key.key_rsa, &n1, NULL, NULL);
 	RSA_get0_key (sk->key_rsa, &n2, NULL, NULL);
 #else
@@ -3035,4 +3035,4 @@
 	}
 
 	return TRUE;
-}
\ no return.
+}

**Comment by androdev4u** [comment]
BUG in gentoo:

https://bugs.gentoo.org/661056

patch file:

https://661056.bugs.gentoo.org/attachment.cgi?id=539780
